global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - "/etc/alerts/*.alert"

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['promserver:9090']

  # Scrape the Node Exporter
  - job_name: 'node1'
    metrics_path: /metrics
    static_configs:
      - targets: ['node1:9100', 'cadvisor:8080']
        labels:
          location: machine1

  # Scrape the Node Exporter
  - job_name: 'node2'
    metrics_path: /metrics
    static_configs:
      - targets: ['node2:9100']
        labels:
          location: machine2

